policy_path: "{LEGGED_GYM_ROOT_DIR}/../unitree_rl_lab/logs/go2_isaacgym/policy_isaaclab.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/../unitree_mujoco/unitree_robots/go2/scene_flat.xml"

simulation_duration: 60.0
simulation_dt: 0.005
control_decimation: 4

kps: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20]
kds: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

default_angles: [0.1, 0.8, -1.5, -0.1, 0.8, -1.5, 0.1, 1.0, -1.5, -0.1, 1.0, -1.5]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]

num_actions: 12
num_obs: 48

cmd_init: [0.5, 0, 0]
